Repository DraftBot/Documentation, pull requests merged in 2023-06, with the labels that each got.

#51 fix changelog
  autres/changelog.md
Labels: corrections

#23 MAJ - Système Tickets
  .gitbook/assets/tickets/ticket-config-menu.png
  .gitbook/assets/tickets/ticket-menu-config.png
  .gitbook/assets/tickets/ticket-menu-no-config.png
  .gitbook/assets/tickets/ticket-open-message.png
  .gitbook/assets/tickets/ticket-panel-config.png
  SUMMARY.md
  modules/tickets.md
  slash/configuration/tickets.md
Labels: améliorations

#55 Correction de l'affichage
  modules/commandes-personnalisees.md
Labels: corrections

#53 Mise à jour du changelog
  autres/changelog.md
Labels: améliorations

#33 Ajout de la page d'anniversaire
  .gitbook/assets/birthday/birth_config_annoncement.png
  .gitbook/assets/birthday/birthday_annoncement_message.png
  .gitbook/assets/birthday/birthday_config_button.png
  .gitbook/assets/birthday/birthday_config_gift.png
  .gitbook/assets/birthday/birthday_config_message_edit.png
  .gitbook/assets/birthday/birthday_config_premium_options.png
  .gitbook/assets/birthday/birthday_config_role.png
  .gitbook/assets/birthday/birthday_config_role_access.png
  .gitbook/assets/birthday/birthday_config_special_annoucement.png
  .gitbook/assets/birthday/birthday_enable.png
  .gitbook/assets/birthday/bithday_config_option_gift.png
  .gitbook/assets/birthday/command_review.png
  SUMMARY.md
  modules/anniversaires.md
Labels: ajout

#52 Ajout du module interserveur
  .gitbook/assets/interservers/interserver_generate.png
  .gitbook/assets/interservers/interserver_link.png
  SUMMARY.md
  modules/interserveurs.md
Labels: ajout

#56 Mise à jour de l'accueil & des commandes.
  README.md
Labels: améliorations, corrections

#32 Ajout de la page des réactions de mots
  .gitbook/assets/wordreact/question.png
  .gitbook/assets/wordreact/view.png
  .gitbook/assets/wordreact/view_panel.png
  .gitbook/assets/wordreact/view_wordreact.jpg
  .gitbook/assets/wordreact/word_deletion.png
  SUMMARY.md
  modules/reactions-de-mots.md
  slash/configuration/reactions-de-mots.md
  slash/wordreact.md
Labels: améliorations

#57 Création de la page "rappel"
  .gitbook/assets/remind/rappel_create.png
  SUMMARY.md
  modules/rappel.md
Labels: ajout

#58 update du changelog
  autres/changelog.md
Labels: ajout

#59 Création de la page "inventaires"
  .gitbook/assets/inventory/dropitem.png
  .gitbook/assets/inventory/inventory.png
  SUMMARY.md
  modules/inventaire.md
Labels: ajout

#60 Amélioration page économie
  modules/economie.md
Labels: améliorations

#61 Création de la page "Compteur de membres"
  .gitbook/assets/membercount/categorycount.png
  .gitbook/assets/membercount/membercount1.png
  SUMMARY.md
  modules/compteur-de-membres.md
Labels: ajout
