Repository DraftBot/Documentation, pull requests merged in 2023-01, with the labels that each got.

#11 Création contenu "Commandes personnalisées"
  slash/commandes-personnalisees.md
Labels: ajout

#10 Correction fautes
  slash/configuration/role-reactions.md
Labels: corrections

#14 Suppression de la page des changelogs
  autres/changelog.md
Labels: suppression

#16 Réécriture de tous les chemins d'images
  .gitbook/assets/Capture1.PNG
  .gitbook/assets/autorole/view.png
  .gitbook/assets/captcha/view.png
  .gitbook/assets/custom-commands/edit-command.png
  .gitbook/assets/custom-commands/home.png
  .gitbook/assets/custom-commands/view.png
  .gitbook/assets/economy/view.png
  .gitbook/assets/levels/view.png
  .gitbook/assets/membercount/view.png
  .gitbook/assets/moderation/view.png
  .gitbook/assets/privateroom/view.png
  .gitbook/assets/report/view.png
  .gitbook/assets/rolereact/question.png
  .gitbook/assets/rolereact/view.png
  .gitbook/assets/socialnotifs/view.png
  .gitbook/assets/suggestions/view.png
  .gitbook/assets/tickets/view.png
  .gitbook/assets/welcome/view.png
  .gitbook/assets/wordreact/question.png
  .gitbook/assets/wordreact/view.png
  prefix/prefixe/commandes-personnalisees.md
  slash/commandes-personnalisees.md
  slash/configuration/arrivees-and-departs.md
  slash/configuration/captcha.md
  slash/configuration/compteur-de-membres.md
  slash/configuration/economie.md
  slash/configuration/moderation.md
  slash/configuration/niveaux.md
  slash/configuration/notifications-sociales.md
  slash/configuration/reactions-de-mots.md
  slash/configuration/role-reactions.md
  slash/configuration/roles-automatiques.md
  slash/configuration/salons-vocaux-temporaires.md
  slash/configuration/signalements.md
  slash/configuration/suggestions.md
  slash/configuration/tickets.md
  slash/wordreact.md
Labels: améliorations

#15 Changement des couleurs
  README.md
  autres/contact.md
  autres/equipe.md
  autres/recuperer-un-identifiant.md
  installation.md
  prefix/prefixe/README.md
  slash/commandes-personnalisees.md
  slash/configuration/README.md
  slash/configuration/anniversaires.md
  slash/configuration/role-reactions.md
  slash/configuration/signalements.md
  slash/gestion-de-leconomie.md
  slash/gestion-des-messages.md
  slash/gestion-des-niveaux.md
  slash/gestion-des-roles.md
  slash/moderation.md
Labels: améliorations

#13 Remplacement de la page equipe par le trombi
  SUMMARY.md
  autres/equipe.md
Labels: suppression
