Repository DraftBot/Documentation, pull requests merged in 2023-09, with the labels that each got.

#69 Mise à jour des variables anniversaires
  modules/anniversaires.md
Labels: améliorations, corrections

#54 Page 💡Suggestions
  .gitbook/assets/suggestions/create_suggestion.png
  .gitbook/assets/suggestions/dashboard_set_structure.png
  .gitbook/assets/suggestions/dashboard_suggestion.png
  .gitbook/assets/suggestions/dashboard_view.png
  .gitbook/assets/suggestions/set_suggestion_automatic_thread.png
  .gitbook/assets/suggestions/set_suggestion_confirmation.png
  .gitbook/assets/suggestions/set_suggestion_member.png
  .gitbook/assets/suggestions/set_suggestion_notification.png
  .gitbook/assets/suggestions/set_suggestion_reactions.png
  .gitbook/assets/suggestions/set_suggestion_sorting.png
  .gitbook/assets/suggestions/suggest_menu.png
  .gitbook/assets/suggestions/suggestion_accept.png
  .gitbook/assets/suggestions/suggestion_confirmation.png
  .gitbook/assets/suggestions/suggestion_planned.png
  .gitbook/assets/suggestions/suggestion_refuse.png
  .gitbook/assets/suggestions/view.png
  SUMMARY.md
  modules/suggestions.md
  slash/configuration/suggestions.md
Labels: améliorations, ajout

#70 Ajout de la page du règlement
  .gitbook/assets/rules/rules-add-1.png
  .gitbook/assets/rules/rules-add-2.png
  .gitbook/assets/rules/rules-create.png
  .gitbook/assets/rules/rules-modify-2.png
  .gitbook/assets/rules/rules-modify.png
  .gitbook/assets/rules/rules-remove.png
  SUMMARY.md
  modules/reglement.md
Labels: ajout
